[template]
src = "nginx-proxy.conf.tmpl"
dest = "/etc/nginx/conf.d/proxy.conf"
keys = [ "/skydns/local/skydns", "/services/nginx/ssl" ]
owner = "root"
mode = "0644"
check_cmd = "nginx -t"
reload_cmd = "bash -c 'for pid in `cat /var/run/nginx.pid`; do kill -HUP $pid; done'"
